name: Web UI Tests on Local Remote Execution

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '00 1 * * *'
  workflow_dispatch:

jobs:
  Run_Web_Tests_Local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'zulu'
          cache: 'maven'
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.4

      - name: Run Web UI Tests on Local Remote Execution
        run: |
          mvn clean test \
            "-DdefaultElementIdentificationTimeout=5" \
            "-DsetParallelMode=DYNAMIC" \
            "-DsetParallel=METHODS" \
            "-DretryMaximumNumberOfAttempts=1" \
            "-DexecutionAddress=localhost:4444" \
            "-DtargetOperatingSystem=LINUX" \
            "-DtargetBrowserName=chrome" \
            "-DheadlessExecution=true" \
            "-DgenerateAllureReportArchive=true" \
            -Dtest=webtestpackage.AiraloWEBTestClass \
            -DexcludeTests=apitestpackage.AiraloAPITest

      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Web_UI_Tests_Local_Allure
          path: "allure-report/*.html"

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "target/surefire-reports/junitreports/TEST-*.xml"
        if: always()
