name: API Tests

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '00 1 * * *'
  workflow_dispatch:

jobs:
  Run_API_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'zulu'
          cache: 'maven'
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.4

      - name: Run API Tests
        run: |
              mvn clean test Dtest=apitestpackage.AiraloAPITest

      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: API_Tests_Allure
          path: "allure-report/*.html"

      - name: Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "target/surefire-reports/junitreports/TEST-*.xml"
