name: Web UI Tests (Docker and Remote Execution)

on:
  pull_request:
    branches: [main]
   
  workflow_dispatch:

jobs:
  Run_Web_UI_Tests_Docker_Remote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'zulu'
          cache: 'maven'
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.4

      - name: Remove Conflicting Docker Packages
        run: |
          sudo apt-get remove -y docker docker-engine docker.io containerd runc

      - name: Set up Docker Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce

      - name: Start Docker Service
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.10.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start Selenium Grid using Docker Compose
        run: |
          docker-compose -f src/main/resources/properties/docker-compose/selenium4.yml up --scale chrome=1 --scale edge=0 --scale firefox=0 -d

      - name: Check Docker Containers
        run: docker ps

      - name: Run Web UI Tests Using Remote Execution
        env:
          baseURL: "https://www.airalo.com/"
        run: |
          mvn clean test \
            -DdefaultElementIdentificationTimeout=0 \
            -DlazyLoadingTimeout=0 \
            -DwaitForLazyLoading=true \
            -DsetParallelMode=DYNAMIC \
            -DclickUsingJavascriptWhenWebDriverClickFails=true \
            -DexecutionAddress=localhost:4444 \
            -DtargetOperatingSystem=LINUX \
            -DtargetBrowserName=chrome \
            -DheadlessExecution=false \
            -DgenerateAllureReportArchive=true \
            -Dtest=webtestpackage.AiraloWEBTestClass

      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Web_UI_Tests_Docker_Remote_Allure
          path: "allure-report/*.html"

      - name: Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "target/surefire-reports/junitreports/TEST-*.xml"
