name: Web UI Tests (Docker and Remote Execution)

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '00 1 * * *'
  workflow_dispatch:

jobs:
  Run_Web_UI_Tests_Docker_Remote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'zulu'
          cache: 'maven'
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Selenium Grid using Docker Compose
        run: |
          docker-compose -f src/main/resources/properties/docker-compose/selenium4.yml up --scale chrome=1 --scale edge=0 --scale firefox=0 -d

      - name: Run Web UI Tests Using Remote Execution
        env:
          baseURL: "https://www.airalo.com/"
        run: |
          mvn clean test -DdefaultElementIdentificationTimeout=5 -DretryMaximumNumberOfAttempts=1 -DexecutionAddress=localhost:4444 -DtargetOperatingSystem=LINUX -DtargetBrowserName=chrome -DheadlessExecution=true -DgenerateAllureReportArchive=true -Dtest=webtestpackage.AiraloWEBTestClass

      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Web_UI_Tests_Docker_Remote_Allure
          path: "allure-report/*.html"

      - name: Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "target/surefire-reports/junitreports/TEST-*.xml"
